### ISSUE TITLE
Open ended sector classification bridge idea

### ISSUE THREAD

**Issue by georgeharris2deg** [RMI-PACTA/r2dii.match#314]
Just floating the idea here. 

Would It be possible to add an open-ended function for a user to create there own sector classification bridge? 
This could be an argument to the Match_name function in the same way that overwrites works

i.e. 
in r2dii.data add a bridge template e.g. r2dii.data::bridge_template
in r2dii.match add an additional argument to match_name e.g. r2dii.match::match_name(lbk, ald, by_sector, min_score, method, p, overwrite, **classification = "r2dii.data::bridge_template"**)

whereby bridge_template is a custom made bridge - this could be a new classification system or even the banks in house one. 

**Why do this?**
Users have varying levels of accuracy in their codes.
Some Users with less technical resources struggle with calculating coverage - by creating their own bridge, they can calculate matching success with relative ease.  
Some Users have codes (internal or external) that are currently not covered by the bridges in r2dii.data - this gives the user more choice.
Gives the User more ownership of the tool. This may be useful in integrating the tool into there system.
Prevents 2dii having to update/adding the bridges all the time.

This is not urgent and currently exists as a "nice to have" 

Thanks!

**Comment by maurolepore** [comment]
It sounds like a great idea -- thanks @georgeharris2deg!

The one implementing the bridges has been @jdhoffa and he may know how much the process he follows could be automated. I suspect it has nuances that are hard to notice in the finished product he delivers; but I'm curious what his view is and I'm happy to help find those "automatable" components.

**Comment by jdhoffa** [comment]
My view is that the easiest way to do this would be to allow the user to identify a sector code system "MANUAL" and just do the bridge themselves to PACTA sectors for each loan:

**Comment by maurolepore** [comment]
Thanks @jdhoffa. Do you have an idea of how much work that is? Maybe add to your estimate the work of adding an article about it?
