### ISSUE TITLE
post-CRAN-acceptance (0.1.4) Follow-up tasks

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/r2dii.match#431]
Following the closure of #430, there are some tasks in #429 that still need to be finished after acceptance to CRAN.

- [x]  Accepted 🎉
- [ ]  Add preemptive link to blog post in pkgdown news menu
- [x]  `usethis::use_github_release()`
- [x]  `usethis::use_dev_version(push = TRUE)`
- [ ]  Finish & Publish blog post

**Comment by jdhoffa** [comment]
Any progress on this?

**Comment by AlexAxthelm** [comment]
@jdhoffa I've not followed up on any of this following acceptance (other fires to deal with, and then it was off my radar). If you add a write a blog post for the repo-level docs, I think George already has one written.

**Comment by jdhoffa** [comment]
I don't think we really use or publicize the blog, to date? I will close this as-is for now. If we want to breath life into the blog we can check that out next release.
