### ISSUE TITLE
Figure out why 9 tests fail

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.match#434]
This PR is the culprit: 
https://github.com/RMI-PACTA/r2dii.match/commit/7a2b5921e933ec3dc4c3a2470ac20ee6cd51f37a

The call to `skip_on_cran()` there seems to skip about 87 tests. 

Without `skip()` (179 total tests, 9 failing):
<img width="327" alt="Screenshot 2024-01-10 at 12 34 07" src="https://github.com/RMI-PACTA/r2dii.match/assets/8741309/a42c1903-5609-47af-89fe-dce7537cfe2b">

with `skip()` (92 total tests, all passing):
<img width="331" alt="Screenshot 2024-01-10 at 12 35 29" src="https://github.com/RMI-PACTA/r2dii.match/assets/8741309/50f5b1e5-047c-4339-b4c8-ab3e43de4335">

Those tests aren't skipped on CI and are why this PR is failing. 

I will look into why all those tests are failing in a separate issue...

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/r2dii.match/issues/433#issuecomment-1885409281_

**Comment by AlexAxthelm** [comment]
FYI, when I run `devtools::test()` from `main` on my machine, I get:
```
R4.3.2> devtools::test()
ℹ Testing r2dii.match
✔ | F W S  OK | Context
✔ |        10 | add_sector_and_borderline
✔ |         7 | check_crucial_names
✔ |         1 | crucial_lbk
✔ |         5 | helper-fake_lbk
✔ |        84 | match_name [2.5s]
✔ |        27 | prioritize
✔ |         7 | restructure_abcd
✔ |         5 | select_chr
✔ |        25 | to_alias
✔ |         4 | uniquify_id_column

══ Results ═══════
Duration: 3.3 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 175 ]
```

**Comment by jdhoffa** [comment]
> FYI, when I run `devtools::test()` from `main` on my machine, I get:
> 
> ```
> R4.3.2> devtools::test()
> ℹ Testing r2dii.match
> ✔ | F W S  OK | Context
> ✔ |        10 | add_sector_and_borderline
> ✔ |         7 | check_crucial_names
> ✔ |         1 | crucial_lbk
> ✔ |         5 | helper-fake_lbk
> ✔ |        84 | match_name [2.5s]
> ✔ |        27 | prioritize
> ✔ |         7 | restructure_abcd
> ✔ |         5 | select_chr
> ✔ |        25 | to_alias
> ✔ |         4 | uniquify_id_column
> 
> ══ Results ═══════
> Duration: 3.3 s
> 
> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 175 ]
> ```

That is running the CRAN installations of both `r2dii.data` and `r2dii.match`?

**Comment by AlexAxthelm** [comment]
Hmm. it appears I was not. I'm also now. seeing failing tests.
