### ISSUE TITLE
upkeep: remove snapshop test

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/r2dii.match#481]
snapshot tests are a hindrance to submitting updates of the r2dii.* suite to CRAN, because of interdependencies between the r2dii packages that may affect the snap results.

we want to remove them.

[AB#11117](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/11117)

**Comment by jdhoffa** [comment]
Related to #392 and [AB#10182](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10182)

**Comment by jdhoffa** [comment]
Also note that this would be a subset of #392 , since snapshots represent some but not all of the tests dependent on `r2dii.data`

**Comment by AlexAxthelm** [comment]
Are aiming to remove all snapshot tests, or just the ones that depend on `r2dii.data`?

**Comment by jdhoffa** [comment]
I think it's safe to just remove the snapshots entirely to be honest, since at best those tests are annoying/ noise that most folks just blindly update, and at worst they give us undue confidence of our testing coverage.

**Comment by jacobvjk** [comment]
I am happy to drop all of them. I feel like the other unit tests are pretty solid for the r2dii.* packages and as @jdhoffa says, they are easier to understand and more purposefully written
